name: Deploy Memvy Website - Development

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        node-version: [20.x]
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn && yarn lint
      - name: build image
        uses: appleboy/ssh-action@master
        env:
          CI_REGISTRY_PASSWORD: ${{ secrets.SECRET_TOKEN }}
          CI_REGISTRY: ghcr.io
          CI_REGISTRY_USER: ${{ vars.CI_REGISTRY_USER }}
          ENVIRONMENT: DEV
          REPLICAS: 1
          NETWORK: umembr-net
        with:
          username: dockeruser
          host: engine.dev.umembrwhen.com
          key: ${{ secrets.SSH_KEY }}
          port: 22 # Defaults to 22
          command_timeout: 120m
          envs: GITHUB_REPOSITORY,GITHUB_SHA,CI_REGISTRY,CI_REGISTRY_USER,CI_REGISTRY_PASSWORD,ENVIRONMENT,REPLICAS,NETWORK
          script: |
            if [ ! -d "website-umembr-develop" ]; then
              git clone https://$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD@github.com/umembr/website-umembr  --branch develop --single-branch website-umembr-develop
            fi
            cd website-umembr-develop
            git fetch && git reset --hard origin/develop
            chmod +x -R ./scripts
            ./scripts/build.sh
      - name: deploy image
        uses: appleboy/ssh-action@master
        env:
          CI_REGISTRY_PASSWORD: ${{ secrets.SECRET_TOKEN }}
          CI_REGISTRY: ghcr.io
          CI_REGISTRY_USER: ${{ vars.CI_REGISTRY_USER }}
          ENVIRONMENT: DEV
          REPLICAS: 1
          NETWORK: umembr-net
        with:
          username: dockeruser
          host: engine.dev.umembrwhen.com
          key: ${{ secrets.SSH_KEY }}
          port: 22 # Defaults to 22
          command_timeout: 120m
          envs: GITHUB_REPOSITORY,GITHUB_SHA,CI_REGISTRY,CI_REGISTRY_USER,CI_REGISTRY_PASSWORD,ENVIRONMENT,REPLICAS,NETWORK
          script: |
            cd website-umembr-develop
            chmod +x -R ./scripts
            ./scripts/deploy.sh
            cd ..
            if [ -d "website-umembr-develop" ]; then rm -rf website-umembr-develop; fi
            exit
            exit

